project:
  type: book
  output-dir: docs

bibliography:
  - ./references/dataSources.bib
  - ./references/RandStatistics.bib
  - ./references/RPackages.bib
  - ./references/referencesFS.bib
  - ./references/referencesIS.bib
  - ./references/evaluation.bib
  - ./references/machinelearning.bib
  - ./references/effortEstimation.bib
  - ./references/DefectPrediction.bib
  - ./references/SEmetrics.bib
link-citations: true

book:
  title: "Data Analysis in Software Engineering using R"
  author:
    - "Daniel Rodriguez"
    - "Javier Dolado"
  description: "DASE Data Analysis in Software Engineering"
  site-url: "https://danrodgar.github.io/DASE/"
  repo-url: "https://github.com/danrodgar/DASE"
  chapters:
    - index.qmd
    - part: "Part I - R Ecosystem"
      chapters:
        - 110_rIntro.qmd
        - 120_intro.qmd
        - 130_rmarkdown.qmd
        - 140_rnpython.qmd
        - 150_rpackages.qmd
        - 160_tidyverse.qmd
        - 170_ggplot.qmd
    - part: "Part II - Data Sources and EDA"
      chapters:
        - 210_dataSources.qmd
        - 220_dataEffortEstimation.qmd
        - 230_exploratoryDataAnalysis.qmd
    - part: "Part III - Preprocessing"
      chapters:
        - 310_basicPreprocessing.qmd
        - 320_advancedPreprocessingTechniques.qmd
        - 330_featureSelectionExample.qmd
    - part: "Part IV - Modeling"
      chapters:
        - 410_basicModelBuildingSupervised.qmd
        - 420_regression.qmd
        - 430_basicModelBuildingUnsupervised.qmd
    - part: "Part V - Evaluation"
      chapters:
        - 510_evaluation.qmd
        - 520_evaluationClassifiers.qmd
        - 530_evaluationGraphical.qmd
        - 540_evaluationRegression.qmd
        - 550_evaluationUnsupervised.qmd
        - 560_classicalHypothesisTesting.qmd
        - 570_evaluationInSoftEng.qmd
        - 580_advancedModelBuilding.qmd
        - 590_SSL.qmd
    - part: "Part VI - Specialized Topics"
      chapters:
        - 610_SNAinSE.qmd
        - 620_textMiningSE.qmd
        - 630_timeSeries.qmd
    - part: "Part VII - References"
      chapters:
        - 990_references.qmd
  appendices:
    - A01_ISBSGPreprocessing.qmd

format:
  html:
    theme: cosmo
    css:
      - style.css
      - toc.css
    toc: true
    number-sections: true

execute:
  enabled: true
  freeze: auto
