---
title: "R and Data Mining Resources"
output: html_document
---



R generic:

[RSeek](http://rseek.org/)
[Google's course](https://www.youtube.com/playlist?list=PLOU2XLYxmsIK9qQfztXeybpHvru-TrqAP)
[swirl](http://swirlstats.com/) package provides an introduction to R by means of interactive courses.

Web Resources:

[http://www.rdatamining.com/](http://www.rdatamining.com/)


Books:

Torgo, Luis, 2020. Data Mining with R: Learning with Case Studies (2nd Edt.). Chapman & Hall/CRC.

Rattle


Popular packages ():


 + e1071 Functions for latent class analysis, short time Fourier transform, fuzzy clustering, support vector machines, shortest path computation, bagged clustering, naive Bayes classifier etc. 

  + rpart Recursive Partitioning and Regression Trees.

  + nnet Feed-forward Neural Networks and Multinomial Log-Linear Models

  + randomForest Breiman and Cutler's random forests for classification and regression

  + caret package (short for Classification And REgression Training) is a set of functions that attempt to streamline the process for creating predictive models
  
  + kernlab Kernel-based Machine Learning Lab

  + glmnet Lasso and elastic-net regularized generalized linear models

  + ROCR Visualizing the performance of scoring classifiers

  + gbm Generalized Boosted Regression Models

  + party A Laboratory for Recursive Partitioning

  + arules Mining Association Rules and Frequent Itemsets

  + tree Classification and regression trees

  + klaR Classification and visualization

  + ipred Improved Predictors
  
  + lars Least Angle Regression, Lasso and Forward Stagewise

  + earth Multivariate Adaptive Regression Spline Models

  + CORElearn Classification, regression, feature evaluation and ordinal evaluation

  + mboost Model-Based Boosting


 + igraph A collection of network analysis tools

