
## Settings thresholds for Defect Prediction


### Use of Mean and Standard Deviation 

Some of the methods proposed in the literature suggest that the threshold for a given measure $X$ should be based on its distribution. 

More specifically, both Erni and Lewerentz [10] and Lanza and Marinescu [19] describe methods to define thresholds based on the mean value and the standard deviation of measures. 

As an applicability precondition, both proposals assume that X follows a normal distribution.
According to [10], the interval $[\mu − \sigma, \mu + \sigma]$ is regarded as the central range of “normal” values for $X$, where $\mu$ and $\sigma$ are the average and the standard deviation of the distribution of $X$, respectively.

The proposal of [19] takes $\mu - \sigma$ as the “low” threshold, $\mu + \sigma$ as the "high" threshold, and $1.5(\mu + \sigma)$ as the "very high"" threshold. In addition, the proposal suggests the use of "meaningful"" thresholds, which can be derived based on

  1. commonly-used fraction thresholds (e.g., 0.75) and 

  2. thresholds with generally-accepted meaning, $\mu - \sigma$ and $\mu + \sigma$.


### Use of Weighted Benchmark Data

Alves et al. use data from multiple different software systems to derive thresholds that are expected to "(i) bring out the metric’s variability between systems and (ii) help focus on a reasonable percentage of the source code volume" [2].


### Use of Quantiles

Quantiles can also be used to set thresholds
